version: '3'
services:
  Disponibilidad:
    image: galeanom26/nicaventa:Nivel4D
    build:
      context: ./Disponibilidad
      dockerfile: Dockerfile
    volumes:
      - ./Disponibilidad/app:/app
    ports:
      - "8000:5000"
    environment:
      - FLASK_DEBUG=1
      - DATABASE_PASSWORD=nicaventaspass
      - DATABASE_NAME=nicaventasdb
      - DATABASE_USER=nicaventasuser
      - DATABASE_HOST=NicaVentas-DB
      - REDIS_LOCATION=redis
      - REDIS_PORT=6379
    command: flask run --host=0.0.0.0
  Condiciones:
    image: galeanom26/nicaventa:Nivel4C
    build:
      context: ./Condiciones
      dockerfile: Dockerfile
    volumes:
      - ./Condiciones/app:/app
    ports:
      - "8001:5000"
    environment:
      - FLASK_DEBUG=1
      - DATABASE_PASSWORD=nicaventaspass
      - DATABASE_NAME=nicaventasdb
      - DATABASE_USER=nicaventasuser
      - DATABASE_HOST=NicaVentas-DB
      - REDIS_LOCATION=redis
      - REDIS_PORT=6379
    command: flask run --host=0.0.0.0
  NicaVentas-DB:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=nv123
      - MYSQL_DATABASE=nicaventasdb
      - MYSQL_USER=nicaventasuser
      - MYSQL_PASSWORD=nicaventaspass
    expose:
      - 3306
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  redis:
    image: redis
    expose:
      - 6379

